language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv update
# command to run tests
script:
  - pipenv run mypy --ignore-missing-imports src/ test/
  - pipenv run pytest --cov=src .
after_success:
  - pipenv run coveralls


notifications:
  slack: guilhermehas:RvkK6mtnuXNoy3tYK8kHPmah
  email: false
