language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv update
# command to run tests
script:
  - pipenv run pytest # or py.test for Python versions 3.5 and below
