language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pipenv
  - pipenv update
# command to run tests
script:
  - pipenv run pytest --cov=crypto .

notifications:
  slack: guilhermehas:RvkK6mtnuXNoy3tYK8kHPmah
  email: false